openapi: 3.0.1
info:
  title: Fitness Tracker API
  version: "1.0"
paths:
  /api/login/:
    post:
      summary: Obtain JWT Token
      responses:
        '200':
          description: Token issued
  /api/register/:
    post:
      summary: Register a user
      responses:
        '201':
          description: User created
  /api/tracker/progress/:
    get:
      summary: Get user progress
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

